services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    volumes:
      - open-webui:/app/backend/data
    restart: always
    environment:
      - WEBUI_SECRET_KEY=changethis
      - OPENAI_API_BASE_URL=http://localhost:8001/v1
      - OPENAI_API_KEY=${VEL_API_KEY}
      - OPENAI_API_BASE_URLS=http://localhost:8001/v1
      - OPENAI_API_KEYS=${VEL_API_KEY}
volumes:
  open-webui:
